name: CI/CD Pipeline for Lamp Stack Application

on: 
  push:
    branches:
      - main

jobs: 
  lint:
    name: Lint PHP Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"
      
      - name: Run PHP_CodeSniffer
        run: phpcs -n src/
  
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v3
      
      - name: Deploy Via SSH
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
        run:
          echo "$SSH_PRIVATE_KEY" > temp_ssh_key
          chmod 600 temp_ssh_key
          ssh -i temp_ssh_key -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST 'sudo bash -s' < deploy/deploy.sh
          rm temp_ssh_key